export const projects = [
    {
        projectName: "Codefolio",
        projectImage: "/Images/Projects/Codefolio.png",
        description: "A centralized platform for tracking and visualizing progress from multiple coding profiles.",
        liveLink: "https://code-folio-insights.vercel.app/",
        repoLink: "https://github.com/VRAJESH-31/CodeFolio-Insights",
        technologies: ["React", "Tailwind CSS", "Zustand", "Bcrypt", "JWT", "Cloudinary", "Express", "MongoDB", "Recharts", "Redis", "Passport.js",],
        domain: ["Website"],
    },
    {
        projectName: "Scrape Spidey",
        projectImage: "/Images/Projects/Scrape-Spidey.png",
        description: "A public api that can fetch the user profile data from different coding platforms like GFG, Interviewbit, Hackerrank and Codechef",
        liveLink: "https://scrape-spidey-documentation.vercel.app/",
        repoLink: "https://github.com/Ashok-Bhatt/ScrapeSpidey",
        technologies: ["React", "Tailwind CSS", "Recharts", "Bcrypt", "JWT", "Express", "MongoDB", "Puppeteer"],
        domain: ["Public API"],
    },
    {
        projectName: "Flavour Fusion",
        projectImage: "/Images/Projects/Flavor-Fusion.jpg",
        description: "A feature-rich recipe app providing an extensive collection of easy-to-follow and diverse recipes for every taste.",
        liveLink: "",
        repoLink: "https://github.com/Ashok-Bhatt/Flavour-Fusion---Recipe-App",
        technologies: ["Android Studio", "Java", "XML", "Firebase"],
        domain: ["Mobile App"],
    },
    {
        projectName: "Kaun Banega Crorepati",
        projectImage: "/Images/Projects/KBC.png",
        description: "An interactive quiz game inspired by Kaun Banega Crorepati, testing knowledge with progressive difficulty levels",
        liveLink: "https://ashok-bhatt.github.io/Kaun-Banega-Crorepati/",
        repoLink: "https://github.com/Ashok-Bhatt/Kaun-Banega-Crorepati",
        technologies: ["HTML", "CSS", "Javascript", "Trivia API"],
        domain: ["Website", "Game"],
    },
    {
        projectName: "Smart Attendance System",
        projectImage: "/Images/Projects/Smart-Attendance-System.webp",
        description: "A web prototype for an automated system to track attendance of students",
        liveLink: "https://smart-attendance-system-mocha.vercel.app/",
        repoLink: "https://github.com/Ashok-Bhatt/Smart-Attendance-System",
        technologies: ["React", "Tailwind CSS", "Face API", "React Webcam", "Flask", "Flask Pymongo", "Hugging Face", "Gradio", "Pillow", "Numpy", "Pandas", "Matplotlib", "Tensorflow"],
        domain: ["Website", "Machine Learning"],
    },
    {
        projectName: "Draw Perfect Circle",
        projectImage: "/Images/Projects/Draw-Perfect-Circle.png",
        description: "A fun game that challenges you to draw the perfect freehand circle",
        liveLink: "https://perfect-circle-two.vercel.app/",
        repoLink: "https://github.com/Ashok-Bhatt/PerfectCircle",
        technologies: ["React", "CSS"],
        domain: ["Website", "Game"],
    },
    {
        projectName: "Listify",
        projectImage: "/Images/Projects/Listify.png",
        description: "A list managing web app built to help users create and manage lists",
        liveLink: "",
        repoLink: "https://github.com/Ashok-Bhatt/Listify",
        technologies: ["React", "Tailwind CSS", "Firebase"],
        domain: ["Website"],
    },
    {
        projectName: "Path Finding Visualizer",
        projectImage: "/Images/Projects/Path-Finding-Visualizer.png",
        description: "A visualizing tool built to visualize a set of path finding algorithms.",
        liveLink: "",
        repoLink: "https://github.com/Ashok-Bhatt/Path-Finding-Visualizer",
        technologies: ["Python", "Tkinter"],
        domain: ["Desktop App"],
    },
    {
        projectName: "Collab Horizon",
        projectImage: "/Images/Projects/Collab-Horizon.png",
        description: "A team project management system where teammates can collaborate on a project",
        liveLink: "",
        repoLink: "https://github.com/Ashok-Bhatt/Collab-Horizon",
        technologies: ["React", "Tailwind CSS", "Bcrypt", "JWT", "Cloudinary", "Express", "MongoDB"],
        domain: ["Website"],
    },
    {
        projectName: "TechSagers",
        projectImage: "/Images/Projects/TechSagers.png",
        description: "A blog website where user can read, create and manage blogs",
        liveLink: "",
        repoLink: "https://github.com/Ashok-Bhatt/TechSagers---Blog-Website",
        technologies: ["React", "Tailwind CSS", "Redux", "TinyMCE Editor", "Appwrite"],
        domain: ["Website"],
    },
    {
        projectName: "Pong Game",
        projectImage: "/Images/Projects/Pong-Game.png",
        description: "A classic two-player arcade game where players aiming to score points by hitting the ball to past the opponent using paddles.",
        liveLink: "",
        repoLink: "https://github.com/Ashok-Bhatt/Pong-Game",
        technologies: ["Python", "Turtle"],
        domain: ["Desktop App", "Game"],
    },
    {
        projectName: "Query Forge",
        projectImage: "/Images/Projects/Query-Forge.png",
        description: "A web service in which user can create chatbot and qna system and then integrate it to other websites using API Keys",
        liveLink: "https://query-forge-five.vercel.app/",
        repoLink: "https://github.com/Ashok-Bhatt/QueryForge",
        technologies: ["React", "Tailwind CSS", "Gemini Flash 2.5", "Puppeteer", "Browserless API", "Express", "JWT", "Bcrypt"],
        domain: ["Website", "Public API"],
    },
];
