export const skills = {
    "Programming Languages": [
        { name: "Python", logoSrc: "/Images/Skills/python_logo.png" },
        { name: "C Language", logoSrc: "/Images/Skills/c_logo.png" },
        { name: "C++", logoSrc: "/Images/Skills/cpp_logo.png" },
        { name: "Java", logoSrc: "/Images/Skills/java_logo.png" },
        { name: "Javascript", logoSrc: "/Images/Skills/javascript_logo.png" },
        { name: "TypeScript", logoSrc: "/Images/Skills/typescript_logo.png" },
    ],
    "Frontend": [
        { name: "HTML", logoSrc: "/Images/Skills/html_logo.png" },
        { name: "CSS", logoSrc: "/Images/Skills/css_logo.png" },
        { name: "Bootstrap", logoSrc: "/Images/Skills/bootstrap_logo.png" },
        { name: "Tailwind", logoSrc: "/Images/Skills/tailwind_logo.png" },
        { name: "React", logoSrc: "/Images/Skills/react_logo.png" },
        { name: "Zustand", logoSrc: "/Images/Skills/zustand_logo.jpg" },
        { name: "Tanstack Query", logoSrc: "/Images/Skills/tanstack_query_logo.png" },
        { name: "Zod", logoSrc: "/Images/Skills/zod_logo.png" },
    ],
    "Backend": [
        { name: "Node", logoSrc: "/Images/Skills/node_logo.png" },
        { name: "Express", logoSrc: "/Images/Skills/express_logo.png" },
        { name: "Firebase", logoSrc: "/Images/Skills/firebase_logo.png" },
        { name: "Flask", logoSrc: "/Images/Skills/flask_logo.png" },
        { name: "JWT", logoSrc: "/Images/Skills/jwt_logo.png" },
        { name: "Passport", logoSrc: "/Images/Skills/passport_logo.png" },
        { name: "Appwrite", logoSrc: "/Images/Skills/appwrite_logo.png" },
    ],
    "Databases": [
        { name: "MongoDB", logoSrc: "/Images/Skills/mongodb_logo.png" },
        { name: "MySQL", logoSrc: "/Images/Skills/mysql.png" },
        { name: "Redis", logoSrc: "/Images/Skills/redis_logo.png" },
    ],
    "Editors": [
        { name: "VS Code", logoSrc: "/Images/Skills/vscode_logo.png" },
        { name: "Android Studio", logoSrc: "/Images/Skills/android_logo.png" },
        { name: "Cursor", logoSrc: "/Images/Skills/cursor_logo.jpg" },
        { name: "Antigravity", logoSrc: "/Images/Skills/antigravity_logo.jpg" },
        { name: "Replit", logoSrc: "/Images/Skills/replit_logo.png" },
    ],
    "Platforms": [
        { name: "Github", logoSrc: "/Images/Skills/github_logo.png" },
        { name: "Vercel", logoSrc: "/Images/Skills/vercel_logo.png" },
        { name: "Render", logoSrc: "/Images/Skills/render_logo.png" },
        { name: "Chatgpt", logoSrc: "/Images/Skills/chatgpt_logo.png" },
        { name: "Gemini", logoSrc: "/Images/Skills/gemini_logo.png" },
        { name: "Cloudinary", logoSrc: "/Images/Skills/cloudinary_logo.png" },
        { name: "Upstash", logoSrc: "/Images/Skills/upstash_logo.png" },
    ],
    "Tools": [
        { name: "Git", logoSrc: "/Images/Skills/git_logo.png" },
        { name: "Postman", logoSrc: "/Images/Skills/postman_logo.png" },
        { name: "Vite", logoSrc: "/Images/Skills/vite_logo.jpg" },
        { name: "Npm", logoSrc: "/Images/Skills/npm_logo.png" },
    ]
};
